traefik:
  image: emilevauge/traefik
  ports:
  - 80:80
  - 8888:8080
  volumes:
  - ./traefik.toml:/traefik.toml
  - /var/run/docker.sock:/tmp/docker.sock

herder:
  image: containersol/herder
  ports:
  - 8077:8080

